### ISSUE TITLE
Click handlers not getting registered

### ISSUE THREAD

**Issue by maevelander** [EnigmaWeb/gift-a-product#6]
From https://wordpress.org/support/topic/click-handlers-not-getting-registered

> The plugin doesn't seem to be working for me. I think it's because the click handlers appear to be added on $(document).ready, but my checkout forms (1 for CC, 1 for Paypal) load async after the ready event fires... so the checkbox never registers the click events.
> 
> Steps to reproduce (staging site w/ only test payments):
> 1. Go to http://staging.mastinlabs.com/store/ and click "Add to Cart" then "Checkout" on any of the items
> 2. See that the "Purchase as gift" checkbox is not functional

**Comment by Base29** [comment]
I think the user has deactivated EDD gift a product ... can you ask the user to activate it again ...

**Comment by maevelander** [comment]
It would be better to replicate this in a test environment of your own rather than relying on the user's site. I think he has provided enough information about the bug for you to do so.

**Comment by maevelander** [comment]
@Base29 any progress on this?

**Comment by Base29** [comment]
Sorry … but cannot replicate this

**Comment by maevelander** [comment]
Ok no worries thanks for trying. Marking it 'cannot replicate' and will close this issue.
