### ISSUE TITLE
New feature: Customise Gift Email Template

### ISSUE THREAD

**Issue by maevelander** [EnigmaWeb/gift-a-product#7]
Add ability to customise gift email template.

**Comment by maevelander** [comment]
Has been done custom for westerly - need to implement to main plugin ASAP

**Comment by maevelander** [comment]
@Base29 any progress on this?

**Comment by Base29** [comment]
Will push today

**Comment by maevelander** [comment]
Great thanks :-)

**Comment by maevelander** [comment]
Implemented in 1.1
